#!/usr/bin/env python3
"""Builds graph/patterns.json: a two-level hierarchy of setting-free story patterns
(themes -> patterns) plus the assignment of every arc to 1-2 patterns (primary first).
Edit the tables below and re-run:  python3 build_patterns.py"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------- level 1: themes
THEMES = [
    ("family_origin", "family and where you come from",
     "How the families we are born into, raised by or measured against shape who we become."),
    ("harm_repair", "harm, guilt and repair",
     "Living with harm done or suffered: guilt, blame, revenge, forgiveness and making amends."),
    ("love_intimacy", "love and intimacy",
     "Wanting, risking, keeping and losing closeness with a partner or someone you love."),
    ("work_purpose", "work, calling and purpose",
     "What we give our working lives to, what it costs, and what gives life meaning."),
    ("leadership_power", "leadership and power",
     "Being put in charge, carrying other people's safety, and what power asks of your conscience."),
    ("loss_grief", "loss and grief",
     "Living through the death or disappearance of people, places and futures you counted on."),
    ("belonging", "belonging and being an outsider",
     "Feeling different, finding your people, and what you will trade to be accepted."),
    ("identity", "identity and self-acceptance",
     "Working out who you are underneath the roles, labels and expectations placed on you."),
    ("control_letting_go", "control and letting go",
     "Holding on too tightly, being controlled by others, and learning to trust and release."),
    ("trauma_recovery", "trauma and recovery",
     "Recovering from violence, abuse, injury, addiction and the defences built to survive them."),
    ("courage_self_worth", "courage and self-worth",
     "Believing you are enough, finding your voice and your own kind of strength."),
    ("duty_vs_desire", "duty vs. the life you want",
     "Obligations and responsibilities pulling against the ordinary life or love you long for."),
    ("caring_guiding", "caring for and guiding others",
     "Parenting, mentoring and looking after people, and how hard it is to do it well."),
]

# ---------------------------------------------------------------- level 2: patterns
# (slug, label, description, [theme slugs])
PATTERNS = [
    # family
    ("approval_from_withholding_parent", "chasing approval from a parent who withholds it",
     "Building your life around winning the love or respect of a parent who keeps withholding it, and wondering what it is costing you.",
     ["family_origin", "courage_self_worth"]),
    ("family_wrote_you_off", "finding your own strength when family has written you off",
     "A family (your own, or the one you hope to join) has decided you don't measure up, and you have to find out what your real strengths are.",
     ["family_origin", "courage_self_worth"]),
    ("measured_against_a_sibling", "always measured against a sibling",
     "Growing up compared with a brother or sister who seems to fit the mould better, and trying to be someone in your own right.",
     ["family_origin", "identity"]),
    ("family_legacy_weight", "living up to, or escaping, a family legacy",
     "Carrying a family name, position or famous parent that decides your worth before you've done anything, and trying to be judged on your own terms.",
     ["family_origin", "identity"]),
    ("family_secret_rewrites_story", "a family secret that rewrites who you thought you were",
     "Learning something hidden about a parent or your own origins that shakes your sense of who you are and where you belong.",
     ["family_origin", "identity"]),
    ("making_peace_with_a_parent", "making peace with an estranged parent or relative",
     "Years of silence, grudges or unfinished business with a parent or relative, and the question of whether you can understand them before time runs out.",
     ["family_origin", "harm_repair"]),
    ("breaking_the_family_cycle", "trying not to repeat what your parents did",
     "Fearing that the anger, coldness or failures of the people who raised you live in you too, and trying to be a different kind of partner or parent.",
     ["family_origin", "trauma_recovery"]),
    ("parentified_child", "the child who had to become the parent",
     "Stepping into the caretaker role far too young, keeping everyone afloat while your own needs and anger go unspoken.",
     ["family_origin", "caring_guiding"]),
    ("tired_of_being_protected", "tired of being the one everyone protects",
     "Being treated as fragile, too young or the one who needs saving, and fighting to show you can stand on your own.",
     ["courage_self_worth", "family_origin"]),
    # caring and guiding
    ("unready_parent", "unready parent, suddenly responsible",
     "Suddenly responsible for a child you didn't plan for, while still working out your own life, and unsure you are fit for it.",
     ["caring_guiding", "family_origin"]),
    ("reluctant_guardian", "a loner who ends up looking after someone",
     "Someone who never planned to care for anyone ends up responsible for a young person, and the bond changes them both.",
     ["caring_guiding", "love_intimacy"]),
    ("guiding_someone_who_resists", "guiding a young person who fights your help",
     "Mentoring or loving a young person who pushes you away, and learning how much to guide, how much to protect and when to trust them.",
     ["caring_guiding", "control_letting_go"]),
    ("protective_love_becomes_control", "protective love that turns into control",
     "A parent or caregiver whose fear for the people in their care turns into rules, control and surveillance that push them away.",
     ["caring_guiding", "control_letting_go"]),
    # control
    ("control_so_no_one_leaves", "grabbing for control whenever you fear losing people",
     "Answering fear of loss or abandonment by tightening your grip on the people around you, even as it drives them off.",
     ["control_letting_go", "love_intimacy"]),
    ("fix_someone_you_cant_save", "trying to fix someone you love when you can't",
     "Watching someone close to you suffer, desperately trying to fix it, and having to learn the limits of what love can do.",
     ["control_letting_go", "love_intimacy"]),
    ("carrying_a_secret_alone", "carrying a hard decision or secret alone",
     "Deciding by yourself what is best for the people you love and hiding it from them, and facing whether that protection was ever really yours to give.",
     ["control_letting_go", "duty_vs_desire"]),
    ("leaving_controlling_group", "leaving a controlling group or person and relearning who you are",
     "After life under someone else's control, learning what you actually think, feel and want, and trusting people who offer a different way to live.",
     ["control_letting_go", "identity"]),
    # harm and repair
    ("earning_back_trust", "earning back trust from the people you hurt",
     "Wanting to make things right with the people you wronged, who have every reason to keep you out, and proving it through actions over time.",
     ["harm_repair", "belonging"]),
    ("can_you_really_change", "trying to become better than your worst past",
     "Carrying real guilt for past harm and trying to live differently, while wondering whether people can truly change.",
     ["harm_repair", "identity"]),
    ("blaming_yourself", "blaming yourself for harm you couldn't prevent",
     "Replaying a moment, a choice or a string of bad luck and believing the losses around you are your fault.",
     ["harm_repair", "loss_grief"]),
    ("guilt_into_care", "turning guilt into care for others",
     "Channelling guilt over people you failed into protecting, teaching or serving others, while still struggling to forgive yourself.",
     ["harm_repair", "caring_guiding"]),
    ("revenge_as_identity", "letting a wound turn into a mission of payback",
     "After being badly hurt, organising your life around making someone pay, until the grudge starts to define who you are.",
     ["harm_repair", "loss_grief"]),
    ("forgive_or_get_even", "deciding whether to forgive, confront or let go",
     "Face to face with the source of your pain, working out what you actually want: justice, an apology, revenge or simply to be free of it.",
     ["harm_repair", "control_letting_go"]),
    # loss and grief
    ("stuck_in_grief", "stuck in grief and afraid to live again",
     "Holding on to a loss so tightly that moving forward, or letting yourself be happy again, feels like a betrayal.",
     ["loss_grief"]),
    ("numb_after_collapse", "going numb after your world falls apart",
     "After a shattering loss, going through the motions, hiding how empty you feel and slowly losing hope.",
     ["loss_grief", "trauma_recovery"]),
    ("taking_stock_of_a_life", "taking stock of the life you chose",
     "Looking back at what you gave up, what you failed at and what you passed on, and asking what your life has meant.",
     ["duty_vs_desire", "loss_grief"]),
    # love
    ("love_you_couldnt_keep", "a love you couldn't keep",
     "Falling hard for someone when circumstances, duty or the truth about them stand in the way, and learning to carry that heartbreak.",
     ["love_intimacy", "loss_grief"]),
    ("letting_love_in", "learning to let love in when you expect it to leave",
     "Someone who learned early that people leave, and who sabotages, runs from or braces against closeness, trying to trust a love that might stay.",
     ["love_intimacy", "trauma_recovery"]),
    ("hidden_love", "loving someone quietly without saying it",
     "Loving a friend or someone you admire for a long time in silence, and weighing the safety of hiding it against the risk of saying it.",
     ["love_intimacy", "courage_self_worth"]),
    ("holding_on_to_someone_pulling_away", "holding on to someone who keeps pulling away",
     "Loving a partner or friend who is guarded, half-committed or walking away, and deciding how long to wait, chase or let go.",
     ["love_intimacy", "control_letting_go"]),
    ("unlikely_bond", "an unlikely bond with someone you started out opposing",
     "A rival or someone you disliked on sight becomes the person who understands you best, in a way neither of you can easily name.",
     ["love_intimacy", "belonging"]),
    ("torn_between_two_loves", "torn between two loves that stand for two versions of you",
     "Caught between two people, each tied to a different life or a different side of yourself, and realising the real choice is about who you want to be.",
     ["love_intimacy", "identity"]),
    ("lost_inside_one_relationship", "a relationship that became your whole identity",
     "Having built your sense of self around one person or relationship, and having to find out who you are without it.",
     ["love_intimacy", "identity"]),
    ("partners_want_different_lives", "a committed relationship pulling apart",
     "A marriage or engagement strained when partners want different futures, grieve in ways the other can't reach, or one of them is frozen by fear of what commitment will turn them into.",
     ["love_intimacy", "duty_vs_desire"]),
    ("rebuilding_after_being_left", "rebuilding yourself after being left",
     "After a partner leaves or a marriage ends, finding your footing, your confidence and your own sense of worth again.",
     ["love_intimacy", "loss_grief"]),
    ("discovering_who_you_love", "discovering who you love and living it openly",
     "Realising something new about who you are attracted to, and deciding whether to live honestly even if others may not accept it.",
     ["identity", "love_intimacy"]),
    # work, calling, duty
    ("calling_vs_love", "when your calling competes with love and family",
     "A demanding career or vocation keeps pulling against a partner, children or the people back home, and every choice gives something up.",
     ["work_purpose", "duty_vs_desire"]),
    ("role_you_never_asked_for", "handed a role you never asked for",
     "Being given a huge responsibility or destiny you didn't choose, and fearing it will swallow the ordinary life and the person you were.",
     ["duty_vs_desire", "identity"]),
    ("dream_isnt_what_promised", "discovering the dream isn't what you were promised",
     "Finally reaching the fresh start, dream place or dream job, and finding it harsher and less welcoming than you imagined.",
     ["work_purpose", "identity"]),
    ("reinvention_after_losing_role", "who you are when the role that defined you is gone",
     "Losing the title, job, fight or status your identity rested on, and having to rebuild meaning from something new.",
     ["work_purpose", "identity"]),
    ("purpose_from_being_needed", "finding a reason to keep going by being useful",
     "At a low point, discovering that being needed by others, or serving something bigger than yourself, can become a reason to live.",
     ["work_purpose", "trauma_recovery"]),
    # leadership and power
    ("promoted_over_peers", "promoted to lead people who used to be your peers",
     "Suddenly in charge of colleagues, friends or people who doubt you, and learning how lonely it is when your calls are resented.",
     ["leadership_power", "work_purpose"]),
    ("weight_of_leading", "carrying the weight of every decision as a leader",
     "Responsible for other people's safety, feeling every loss as your own, and struggling to share the load or accept that you can't control every outcome.",
     ["leadership_power", "control_letting_go"]),
    ("crossing_a_line_under_pressure", "pressured to cross a line your conscience forbids",
     "Everyone agrees on the 'necessary' choice and it is the one thing your principles reject, and you have to decide what you can live with.",
     ["leadership_power", "identity"]),
    ("conscience_vs_institution", "choosing your conscience over the institution you serve",
     "Loyal to an organisation, a leader or its rules, until they collide with what you know is right for a person in front of you.",
     ["work_purpose", "leadership_power"]),
    ("complicit_in_bad_organisation", "working for a boss or group whose methods you can't stomach",
     "Staying inside an organisation, cause or boss that does harm, telling yourself you can do good from within, and deciding when to walk away.",
     ["work_purpose", "leadership_power"]),
    # belonging, courage, identity
    ("fighting_for_respect", "fighting for respect in a place that says you don't belong",
     "Pushing into a path, team or role usually closed to people like you, and demanding to be treated as a full person rather than a tool or a joke.",
     ["belonging", "courage_self_worth"]),
    ("ordinary_among_gifted", "feeling ordinary among naturally gifted people",
     "Surrounded by people with obvious talent, feeling you bring nothing special, and working out what your own strengths really are.",
     ["courage_self_worth", "belonging"]),
    ("worth_only_when_winning", "believing you're only worth something when you succeed",
     "An identity built on being the best or living up to a role, where every setback feels like proof you are nothing without it.",
     ["courage_self_worth", "identity"]),
    ("outsider_learning_to_belong", "the outsider studying others to learn how to belong",
     "Someone who feels fundamentally different treats ordinary social life as something to learn, and wonders whether to become like others or be accepted as they are.",
     ["belonging", "identity"]),
    ("between_two_worlds", "caught between two cultures or families that each claim you",
     "Belonging to two worlds and fully to neither, suppressing or idealising one side of yourself while trying to choose which values are really yours.",
     ["belonging", "family_origin"]),
    ("giving_yourself_up_to_belong", "how much of yourself you'll give up to belong",
     "Hungry to be accepted by a group, and discovering the price of admission is your honesty, your name or your sense of who you are.",
     ["belonging", "identity"]),
    ("starving_to_matter", "starving to be recognised as someone who matters",
     "After a life of being overlooked, rejected or blamed, needing desperately to be seen as special or chosen, and what that hunger makes you do.",
     ["belonging", "courage_self_worth"]),
    ("dropping_the_armour", "dropping the armour you built after early rejection",
     "Someone who learned young that caring makes you weak hides behind coldness, arrogance or distance, and slowly risks letting people in.",
     ["trauma_recovery", "love_intimacy"]),
    ("find_your_voice", "finding your voice after being silenced",
     "Someone who was expected to stay quiet, obedient or decorative slowly learns to speak up and take charge of their own life.",
     ["courage_self_worth", "control_letting_go"]),
    # trauma and recovery
    ("relearning_safety_after_abuse", "learning to feel safe again after abuse",
     "After abuse, captivity or violence, rebuilding a life and learning whether it is safe to be close to people and to be known.",
     ["trauma_recovery", "control_letting_go"]),
    ("strong_one_cracks", "when the strong, capable one starts to crack",
     "Someone whose identity rests on being strong and competent hits a breaking point, and has to admit they need help.",
     ["trauma_recovery", "identity"]),
    ("pretending_fine_after_trauma", "insisting you're fine after something terrible",
     "After a violent or violating experience, throwing yourself back into life as if nothing changed, until it breaks through and hurts the people close to you.",
     ["trauma_recovery"]),
    ("body_blow", "rebuilding yourself after a body or health blow",
     "An injury or illness takes away the ability your life was built on, and you have to work out who you are in the body you have now.",
     ["trauma_recovery", "identity"]),
    ("numbing_habit", "numbing pain with a habit that takes over",
     "Reaching for a drink, a drug, food or a feeling of power to cope, hiding it from people who depend on you, and fighting to get and stay clean.",
     ["trauma_recovery", "control_letting_go"]),
    # added with the second batch of shows
    ("persona_replacing_you", "a role or persona that starts to replace who you are",
     "Playing a part, a louder version of yourself or a whole double life so long and so well that the gap between the person you show and the person you are threatens to swallow you.",
     ["identity", "duty_vs_desire"]),
    ("longing_for_a_family_of_your_own", "longing for a family that won't arrive the way you pictured",
     "Wanting a partner, a child or a home of your own while timing, bodies, loss or the wrong relationships keep getting in the way, and deciding what family can look like instead.",
     ["love_intimacy", "family_origin"]),
    ("betting_on_yourself", "leaving the safe path to bet on yourself",
     "Walking away from a comfortable, expected or dead-end life to chase work or a life that actually fits you, with no guarantee and plenty of people saying it's a mistake.",
     ["work_purpose", "courage_self_worth"]),
    ("outrunning_pain", "staying in motion so the pain can't catch up",
     "Keeping busy, cheerful, reckless or always on the move so that old pain or fresh grief never has to be felt, until it starts leaking out anyway.",
     ["loss_grief", "trauma_recovery"]),
    ("second_chance_as_a_parent", "a second chance to be the parent you weren't",
     "A parent who was absent, self-absorbed or cut off from their child by their own choices gets a late chance to be close, and has to find out whether it is too late.",
     ["caring_guiding", "harm_repair"]),
    ("learning_what_you_deserve_in_love", "learning what you deserve in love",
     "Staying with people who neglect, belittle or take you for granted, waiting to be chosen, and slowly learning to name what you need and walk away from less.",
     ["love_intimacy", "courage_self_worth"]),
    ("shoes_you_cant_fill", "stepping into shoes you feel you can't fill",
     "Handed the place, work or trust of someone you admired, haunted by comparison and the feeling it should have gone to someone better, and trying to do it your own way.",
     ["leadership_power", "courage_self_worth"]),
    ("loving_family_who_do_harm", "loving a family member who does harm",
     "Discovering that someone in your family has hurt you or other people, and working out how much of them you can keep loving, defending or letting close without betraying yourself.",
     ["family_origin", "harm_repair"]),
    ("trusting_your_instincts", "trusting your instincts when no one believes you",
     "Sensing that something is badly wrong while everyone around you calls it worry, nagging or hysteria, and deciding whether to trust what you see and act on it.",
     ["courage_self_worth"]),
    ("power_going_to_your_head", "letting power or status go to your head",
     "Hungry for authority, or suddenly free of anyone to check you, starting to believe the rules don't apply and treating people as tools, and finding out what real responsibility asks.",
     ["leadership_power", "identity"]),
    # added with the third batch of shows
    ("fear_making_your_choices", "when fear starts making your choices for you",
     "Anxiety about getting it wrong, getting hurt or facing a big change freezes you in place or sends you into a panic at every step forward, and you have to learn to act, commit and live with uncertainty.",
     ["courage_self_worth", "control_letting_go"]),
    ("finally_growing_up", "the lovable one who finally has to grow up",
     "Coasting on charm, jokes or impulse while other people carry the adult responsibilities, and learning to become someone others can rely on without losing the joy that made people love you.",
     ["identity", "duty_vs_desire"]),
    ("helper_with_no_needs", "the helper who never asks for anything",
     "Always the one who listens, fixes, calms and puts everyone else first, until you realise you have never asked what you want or let anyone look after you.",
     ["caring_guiding", "courage_self_worth"]),
    ("adrift_looking_for_a_calling", "drifting and searching for work that feels like yours",
     "Unsure what you are good at or what you actually want, drifting through jobs or plans that don't fit, and trying to find a purpose that belongs to you rather than to other people's expectations.",
     ["work_purpose", "identity"]),
    ("affair_breaks_the_trust", "an affair or hidden life that breaks a marriage's trust",
     "A partner's affair or long-kept secret cracks open a marriage, and both the one who strayed and the one betrayed have to face the harm and decide what, if anything, can be rebuilt.",
     ["love_intimacy", "harm_repair"]),
]

# ---------------------------------------------------------------- arc assignments
# arc id (without "arc:") -> [primary pattern, optional secondary]
ASSIGN = {
    # Avatar
    "avatar/aang/reluctant_chosen_one": ["role_you_never_asked_for"],
    "avatar/aang/last_of_his_people": ["stuck_in_grief", "blaming_yourself"],
    "avatar/aang/values_under_pressure": ["crossing_a_line_under_pressure"],
    "avatar/katara/parentified_caretaker": ["parentified_child"],
    "avatar/katara/fighting_to_be_taught": ["fighting_for_respect"],
    "avatar/katara/revenge_or_release": ["forgive_or_get_even"],
    "avatar/zuko/fathers_approval": ["approval_from_withholding_parent"],
    "avatar/zuko/earning_trust_back": ["earning_back_trust"],
    "avatar/sokka/ordinary_among_gifted": ["ordinary_among_gifted"],
    "avatar/sokka/love_you_cant_keep": ["love_you_couldnt_keep", "blaming_yourself"],
    "avatar/toph_beifong/breaking_out_of_the_cage": ["tired_of_being_protected"],
    "avatar/toph_beifong/making_amends_as_a_parent": ["breaking_the_family_cycle"],
    "avatar/iroh/loving_someone_who_pushes_you_away": ["guiding_someone_who_resists"],
    "avatar/iroh/from_power_to_peace": ["reinvention_after_losing_role"],
    "avatar/azula/the_perfect_daughter": ["worth_only_when_winning", "measured_against_a_sibling"],
    "avatar/azula/ruling_by_fear": ["control_so_no_one_leaves"],
    "avatar/korra/hothead_in_training": ["worth_only_when_winning", "role_you_never_asked_for"],
    "avatar/korra/healing_after_trauma": ["strong_one_cracks", "body_blow"],
    "avatar/tenzin/teaching_his_opposite": ["guiding_someone_who_resists"],
    "avatar/tenzin/fathers_shadow": ["family_legacy_weight"],
    "avatar/asami_sato/fathers_betrayal": ["family_secret_rewrites_story", "forgive_or_get_even"],
    "avatar/asami_sato/rival_to_closest_friend": ["unlikely_bond"],
    "avatar/lin_beifong/duty_above_all": ["reinvention_after_losing_role", "dropping_the_armour"],
    "avatar/lin_beifong/old_family_wounds": ["making_peace_with_a_parent", "measured_against_a_sibling"],
    "avatar/bolin/little_brother_finding_his_worth": ["measured_against_a_sibling", "tired_of_being_protected"],
    "avatar/bolin/following_the_wrong_leader": ["complicit_in_bad_organisation", "earning_back_trust"],
    # Buffy / Angel
    "buffy/buffy_summers/reluctant_chosen_one": ["role_you_never_asked_for"],
    "buffy/buffy_summers/first_love_turns": ["love_you_couldnt_keep"],
    "buffy/buffy_summers/finding_reason_to_live": ["numb_after_collapse", "parentified_child"],
    "buffy/angel/atonement_for_the_past": ["can_you_really_change", "guilt_into_care"],
    "buffy/angel/unexpected_fatherhood": ["unready_parent", "can_you_really_change"],
    "buffy/willow_rosenberg/wallflower_finds_herself": ["discovering_who_you_love", "hidden_love"],
    "buffy/willow_rosenberg/power_becomes_addiction": ["numbing_habit"],
    "buffy/spike/monster_to_man": ["can_you_really_change", "holding_on_to_someone_pulling_away"],
    "buffy/spike/proving_himself_to_the_one_who_made_him": ["can_you_really_change"],
    "buffy/rupert_giles/mentor_becomes_father": ["conscience_vs_institution", "reluctant_guardian"],
    "buffy/rupert_giles/when_theyre_grown": ["reinvention_after_losing_role"],
    "buffy/alexander_harris/left_behind_after_school": ["ordinary_among_gifted"],
    "buffy/alexander_harris/fear_of_becoming_his_parents": ["breaking_the_family_cycle", "partners_want_different_lives"],
    "buffy/cordelia_chase/popularity_or_real_friends": ["giving_yourself_up_to_belong"],
    "buffy/cordelia_chase/from_fame_to_calling": ["purpose_from_being_needed", "reinvention_after_losing_role"],
    "buffy/faith_lehane/looking_for_a_family": ["giving_yourself_up_to_belong", "starving_to_matter"],
    "buffy/faith_lehane/facing_what_she_did": ["can_you_really_change"],
    "buffy/dawn_summers/am_i_real": ["family_secret_rewrites_story"],
    "buffy/dawn_summers/earning_her_place": ["tired_of_being_protected", "starving_to_matter"],
    "buffy/wesley_wyndam_pryce/never_good_enough": ["worth_only_when_winning", "approval_from_withholding_parent"],
    "buffy/wesley_wyndam_pryce/the_hard_call_alone": ["carrying_a_secret_alone"],
    "buffy/anya_jenkins/learning_to_be_human": ["outsider_learning_to_belong", "lost_inside_one_relationship"],
    "buffy/anya_jenkins/owning_her_life": ["lost_inside_one_relationship", "rebuilding_after_being_left"],
    "buffy/winifred_burkle/coming_back_to_life": ["relearning_safety_after_abuse", "forgive_or_get_even"],
    "buffy/winifred_burkle/big_job_inside_the_machine": ["complicit_in_bad_organisation"],
    # Game of Thrones
    "game_of_thrones/daenerys_targaryen/finding_her_voice": ["find_your_voice"],
    "game_of_thrones/daenerys_targaryen/learning_to_rule": ["weight_of_leading", "crossing_a_line_under_pressure"],
    "game_of_thrones/daenerys_targaryen/the_price_of_destiny": ["starving_to_matter"],
    "game_of_thrones/tyrion_lannister/the_unwanted_son": ["approval_from_withholding_parent"],
    "game_of_thrones/tyrion_lannister/rock_bottom_and_purpose": ["purpose_from_being_needed"],
    "game_of_thrones/tyrion_lannister/advising_the_one_he_believes_in": ["conscience_vs_institution"],
    "game_of_thrones/jon_snow/looking_for_belonging": ["dream_isnt_what_promised", "between_two_worlds"],
    "game_of_thrones/jon_snow/leading_those_who_resent_him": ["promoted_over_peers"],
    "game_of_thrones/jon_snow/love_duty_and_identity": ["role_you_never_asked_for", "family_secret_rewrites_story"],
    "game_of_thrones/jaime_lannister/losing_what_defined_him": ["body_blow"],
    "game_of_thrones/jaime_lannister/love_that_consumes": ["lost_inside_one_relationship"],
    "game_of_thrones/cersei_lannister/a_mother_fighting_for_control": ["protective_love_becomes_control"],
    "game_of_thrones/cersei_lannister/holding_on_at_any_cost": ["control_so_no_one_leaves"],
    "game_of_thrones/sansa_stark/fairy_tale_to_cage": ["dream_isnt_what_promised", "find_your_voice"],
    "game_of_thrones/sansa_stark/taking_her_life_back": ["relearning_safety_after_abuse"],
    "game_of_thrones/sansa_stark/stepping_into_leadership": ["promoted_over_peers", "weight_of_leading"],
    "game_of_thrones/arya_stark/list_of_names": ["revenge_as_identity"],
    "game_of_thrones/arya_stark/becoming_no_one": ["giving_yourself_up_to_belong"],
    "game_of_thrones/arya_stark/the_other_sister": ["measured_against_a_sibling"],
    "game_of_thrones/theon_greyjoy/two_families": ["approval_from_withholding_parent", "between_two_worlds"],
    "game_of_thrones/theon_greyjoy/losing_his_name": ["leaving_controlling_group", "relearning_safety_after_abuse"],
    "game_of_thrones/theon_greyjoy/earning_forgiveness": ["earning_back_trust", "purpose_from_being_needed"],
    "game_of_thrones/brienne_of_tarth/proving_herself": ["fighting_for_respect"],
    "game_of_thrones/brienne_of_tarth/keeping_the_promise": ["guilt_into_care"],
    "game_of_thrones/brienne_of_tarth/unlikely_bond": ["unlikely_bond"],
    "game_of_thrones/samwell_tarly/courage_his_own_way": ["family_wrote_you_off"],
    "game_of_thrones/samwell_tarly/dream_institution": ["dream_isnt_what_promised", "conscience_vs_institution"],
    "game_of_thrones/sandor_clegane/cruel_boss": ["complicit_in_bad_organisation"],
    "game_of_thrones/sandor_clegane/reluctant_guardian": ["reluctant_guardian"],
    "game_of_thrones/sandor_clegane/second_chance": ["can_you_really_change", "revenge_as_identity"],
    "game_of_thrones/bran_stark/after_the_fall": ["body_blow"],
    "game_of_thrones/bran_stark/the_burden": ["role_you_never_asked_for"],
    # Grey's Anatomy
    "greys_anatomy/meredith_grey/letting_love_in": ["letting_love_in"],
    "greys_anatomy/meredith_grey/living_again_after_loss": ["stuck_in_grief"],
    "greys_anatomy/meredith_grey/breaking_rules_for_right_reasons": ["conscience_vs_institution"],
    "greys_anatomy/miranda_bailey/career_and_motherhood": ["calling_vs_love"],
    "greys_anatomy/miranda_bailey/leading_the_hospital": ["promoted_over_peers"],
    "greys_anatomy/miranda_bailey/strong_one_asks_for_help": ["strong_one_cracks"],
    "greys_anatomy/richard_webber/sobriety": ["numbing_habit"],
    "greys_anatomy/richard_webber/wife_slipping_away": ["fix_someone_you_cant_save"],
    "greys_anatomy/richard_webber/pushed_aside": ["reinvention_after_losing_role"],
    "greys_anatomy/alex_karev/tough_guy_softens": ["dropping_the_armour", "parentified_child"],
    "greys_anatomy/alex_karev/not_his_father": ["breaking_the_family_cycle"],
    "greys_anatomy/alex_karev/partner_in_depression": ["fix_someone_you_cant_save"],
    "greys_anatomy/owen_hunt/bringing_war_home": ["pretending_fine_after_trauma"],
    "greys_anatomy/owen_hunt/wanting_a_family": ["partners_want_different_lives"],
    "greys_anatomy/owen_hunt/distrusting_joy": ["letting_love_in"],
    "greys_anatomy/derek_shepherd/starting_over_after_betrayal": ["torn_between_two_loves"],
    "greys_anatomy/derek_shepherd/trauma_and_recklessness": ["pretending_fine_after_trauma"],
    "greys_anatomy/derek_shepherd/sacrifice_and_resentment": ["calling_vs_love", "taking_stock_of_a_life"],
    "greys_anatomy/cristina_yang/work_first_love_second": ["calling_vs_love"],
    "greys_anatomy/cristina_yang/after_the_trauma": ["strong_one_cracks"],
    "greys_anatomy/cristina_yang/outgrowing_home": ["calling_vs_love"],
    "greys_anatomy/amelia_shepherd/out_of_the_shadow": ["measured_against_a_sibling", "numbing_habit"],
    "greys_anatomy/amelia_shepherd/marriage_and_the_tumor": ["partners_want_different_lives"],
    "greys_anatomy/amelia_shepherd/choosing_her_own_shape": ["partners_want_different_lives"],
    "greys_anatomy/callie_torres/loving_someone_who_doesnt_choose_you": ["holding_on_to_someone_pulling_away"],
    "greys_anatomy/callie_torres/coming_out": ["discovering_who_you_love"],
    "greys_anatomy/callie_torres/after_the_impossible_choice": ["fix_someone_you_cant_save"],
    "greys_anatomy/jackson_avery/beyond_the_family_name": ["family_legacy_weight"],
    "greys_anatomy/jackson_avery/grief_and_a_marriage": ["partners_want_different_lives", "stuck_in_grief"],
    "greys_anatomy/jo_wilson/learning_to_be_safe": ["relearning_safety_after_abuse", "letting_love_in"],
    "greys_anatomy/jo_wilson/finding_where_you_came_from": ["family_secret_rewrites_story", "numb_after_collapse"],
    "greys_anatomy/jo_wilson/left_behind_and_rebuilding": ["rebuilding_after_being_left"],
    "greys_anatomy/arizona_robbins/losing_part_of_yourself": ["body_blow"],
    "greys_anatomy/arizona_robbins/starting_over_single": ["rebuilding_after_being_left"],
    # Naruto
    "naruto/naruto_uzumaki/earning_acknowledgement": ["starving_to_matter"],
    "naruto/naruto_uzumaki/never_giving_up_on_a_friend": ["holding_on_to_someone_pulling_away"],
    "naruto/naruto_uzumaki/grief_and_the_cycle_of_hatred": ["forgive_or_get_even"],
    "naruto/sasuke_uchiha/living_for_revenge": ["revenge_as_identity"],
    "naruto/sasuke_uchiha/coming_back_from_darkness": ["earning_back_trust"],
    "naruto/sakura_haruno/tired_of_being_saved": ["tired_of_being_protected", "ordinary_among_gifted"],
    "naruto/sakura_haruno/loving_someone_who_pushes_you_away": ["holding_on_to_someone_pulling_away"],
    "naruto/kakashi_hatake/teaching_the_lesson_that_cost_everything": ["guilt_into_care"],
    "naruto/kakashi_hatake/making_peace_with_a_disgraced_father": ["making_peace_with_a_parent"],
    "naruto/hinata_hyuga/courage_when_family_gave_up": ["family_wrote_you_off"],
    "naruto/hinata_hyuga/loving_from_afar": ["hidden_love"],
    "naruto/rock_lee/hard_work_vs_talent": ["ordinary_among_gifted"],
    "naruto/rock_lee/when_your_body_fails_you": ["body_blow"],
    "naruto/gaara/the_boy_they_called_a_monster": ["dropping_the_armour"],
    "naruto/gaara/leading_those_who_feared_him": ["promoted_over_peers", "earning_back_trust"],
    "naruto/shikamaru_nara/reluctant_leader": ["promoted_over_peers"],
    "naruto/shikamaru_nara/losing_a_mentor": ["forgive_or_get_even"],
    "naruto/itachi_uchiha/the_brother_who_chose_to_be_hated": ["carrying_a_secret_alone"],
    "naruto/neji_hyuga/breaking_free_from_fate": ["family_legacy_weight"],
    "naruto/jiraiya/the_reluctant_father_figure": ["reluctant_guardian"],
    "naruto/jiraiya/a_life_measured_in_failures": ["taking_stock_of_a_life"],
    "naruto/tsunade/the_healer_who_stopped_believing": ["numb_after_collapse"],
    "naruto/tsunade/sending_loved_ones_into_danger": ["weight_of_leading"],
    # Attack on Titan
    "attack_on_titan/eren_yeager/channeling_helplessness_into_rage": ["revenge_as_identity"],
    "attack_on_titan/eren_yeager/pushing_everyone_away": ["carrying_a_secret_alone", "role_you_never_asked_for"],
    "attack_on_titan/mikasa_ackerman/protecting_her_only_family": ["lost_inside_one_relationship"],
    "attack_on_titan/mikasa_ackerman/loving_someone_who_is_changing": ["holding_on_to_someone_pulling_away"],
    "attack_on_titan/armin_arlert/finding_his_worth": ["ordinary_among_gifted"],
    "attack_on_titan/armin_arlert/standing_in_a_greater_place": ["shoes_you_cant_fill"],
    "attack_on_titan/levi/carrying_the_fallen": ["weight_of_leading"],
    "attack_on_titan/levi/the_man_who_raised_him": ["breaking_the_family_cycle"],
    "attack_on_titan/hange_zoe/curiosity_over_hatred": ["forgive_or_get_even"],
    "attack_on_titan/hange_zoe/leading_after_a_legend": ["shoes_you_cant_fill", "weight_of_leading"],
    "attack_on_titan/reiner_braun/the_dependable_one": ["persona_replacing_you", "strong_one_cracks"],
    "attack_on_titan/reiner_braun/guilt_and_the_will_to_live": ["can_you_really_change", "purpose_from_being_needed"],
    "attack_on_titan/erwin_smith/a_dream_worth_the_cost": ["weight_of_leading"],
    "attack_on_titan/historia/the_girl_behind_the_kindness": ["giving_yourself_up_to_belong"],
    "attack_on_titan/historia/choosing_her_own_path": ["approval_from_withholding_parent", "family_legacy_weight"],
    # BoJack Horseman
    "bojack/bojack_horseman/wanting_to_be_loved_while_hating_himself": ["can_you_really_change", "numbing_habit"],
    "bojack/bojack_horseman/still_waiting_for_his_mother": ["approval_from_withholding_parent", "making_peace_with_a_parent"],
    "bojack/bojack_horseman/getting_sober_and_facing_the_harm": ["numbing_habit", "can_you_really_change"],
    "bojack/diane_nguyen/wanting_her_work_to_matter": ["worth_only_when_winning", "dream_isnt_what_promised"],
    "bojack/diane_nguyen/carrying_the_damage_from_home": ["family_wrote_you_off", "numb_after_collapse"],
    "bojack/diane_nguyen/loving_someone_so_different": ["partners_want_different_lives"],
    "bojack/princess_carolyn/the_one_who_holds_it_together": ["strong_one_cracks"],
    "bojack/princess_carolyn/wanting_to_be_a_mother": ["longing_for_a_family_of_your_own"],
    "bojack/todd_chavez/drifting_on_a_friends_couch": ["giving_yourself_up_to_belong"],
    "bojack/todd_chavez/not_feeling_what_others_feel": ["discovering_who_you_love"],
    "bojack/mr_peanutbutter/learning_to_be_alone": ["outrunning_pain", "lost_inside_one_relationship"],
    "bojack/hollyhock/searching_for_where_she_comes_from": ["family_secret_rewrites_story"],
    "bojack/hollyhock/protecting_herself_from_someone_she_loves": ["loving_family_who_do_harm", "relearning_safety_after_abuse"],
    # Breaking Bad / Better Call Saul
    "breaking_bad/walter_white/the_overlooked_man_wants_his_due": ["starving_to_matter", "taking_stock_of_a_life"],
    "breaking_bad/walter_white/the_double_life_at_home": ["carrying_a_secret_alone", "persona_replacing_you"],
    "breaking_bad/jesse_pinkman/proving_hes_more_than_a_screwup": ["family_wrote_you_off", "leaving_controlling_group"],
    "breaking_bad/jesse_pinkman/carrying_guilt_he_cant_put_down": ["can_you_really_change", "numbing_habit"],
    "breaking_bad/skyler_white/the_wife_who_notices": ["trusting_your_instincts"],
    "breaking_bad/skyler_white/complicit_to_protect_her_kids": ["crossing_a_line_under_pressure", "complicit_in_bad_organisation"],
    "breaking_bad/hank_schrader/the_tough_guy_who_cant_admit_fear": ["strong_one_cracks", "pretending_fine_after_trauma"],
    "breaking_bad/hank_schrader/the_case_he_cant_let_go": ["calling_vs_love", "loving_family_who_do_harm"],
    "breaking_bad/jimmy_mcgill/the_little_brother_never_good_enough": ["measured_against_a_sibling"],
    "breaking_bad/jimmy_mcgill/the_mask_that_becomes_the_man": ["persona_replacing_you", "can_you_really_change"],
    "breaking_bad/mike_ehrmantraut/living_for_his_granddaughter": ["guilt_into_care", "blaming_yourself"],
    "breaking_bad/mike_ehrmantraut/the_professional_with_a_code": ["complicit_in_bad_organisation"],
    "breaking_bad/kim_wexler/climbing_on_her_own_terms": ["fighting_for_respect", "dream_isnt_what_promised"],
    "breaking_bad/kim_wexler/loving_someone_who_brings_out_your_wild_side": ["torn_between_two_loves"],
    "breaking_bad/walter_white_jr/the_kid_left_out_of_the_family_secret": ["family_secret_rewrites_story", "tired_of_being_protected"],
    # Doctor Who
    "doctor_who/tenth_doctor/charm_over_grief": ["outrunning_pain", "letting_love_in"],
    "doctor_who/tenth_doctor/alone_and_unchecked": ["power_going_to_your_head", "taking_stock_of_a_life"],
    "doctor_who/twelfth_doctor/am_i_a_good_man": ["can_you_really_change"],
    "doctor_who/twelfth_doctor/cannot_let_her_go": ["control_so_no_one_leaves", "stuck_in_grief"],
    "doctor_who/twelfth_doctor/keeping_his_word": ["purpose_from_being_needed", "taking_stock_of_a_life"],
    "doctor_who/rose_tyler/outgrowing_a_small_life": ["betting_on_yourself", "calling_vs_love"],
    "doctor_who/rose_tyler/love_she_cannot_name": ["love_you_couldnt_keep", "hidden_love"],
    "doctor_who/martha_jones/waiting_to_be_seen": ["holding_on_to_someone_pulling_away", "learning_what_you_deserve_in_love"],
    "doctor_who/martha_jones/holding_everyone_together": ["parentified_child", "role_you_never_asked_for"],
    "doctor_who/donna_noble/just_a_temp": ["family_wrote_you_off", "ordinary_among_gifted"],
    "doctor_who/amy_pond/left_waiting": ["letting_love_in"],
    "doctor_who/amy_pond/future_she_planned": ["longing_for_a_family_of_your_own", "partners_want_different_lives"],
    "doctor_who/rory_williams/in_someone_elses_shadow": ["ordinary_among_gifted"],
    "doctor_who/rory_williams/quiet_man_stands_up": ["find_your_voice"],
    "doctor_who/clara_oswald/carer_who_never_left": ["parentified_child"],
    "doctor_who/clara_oswald/living_a_double_life": ["persona_replacing_you", "carrying_a_secret_alone"],
    "doctor_who/clara_oswald/outrunning_grief": ["outrunning_pain"],
    # Friends
    "friends/rachel_green/building_a_life_of_her_own": ["betting_on_yourself", "tired_of_being_protected"],
    "friends/rachel_green/love_with_a_close_friend": ["holding_on_to_someone_pulling_away", "love_you_couldnt_keep"],
    "friends/monica_geller/wanting_a_family": ["longing_for_a_family_of_your_own"],
    "friends/monica_geller/never_good_enough_for_mom": ["approval_from_withholding_parent", "measured_against_a_sibling"],
    "friends/monica_geller/earning_respect_at_work": ["promoted_over_peers"],
    "friends/phoebe_buffay/finding_family_after_a_hard_start": ["making_peace_with_a_parent"],
    "friends/phoebe_buffay/carrying_a_gift_for_someone_else": ["longing_for_a_family_of_your_own"],
    "friends/phoebe_buffay/wanting_a_love_with_a_future": ["partners_want_different_lives", "torn_between_two_loves"],
    "friends/joey_tribbiani/chasing_the_big_break": ["betting_on_yourself"],
    "friends/joey_tribbiani/falling_for_a_friend": ["hidden_love"],
    "friends/chandler_bing/afraid_of_commitment": ["letting_love_in", "breaking_the_family_cycle"],
    "friends/chandler_bing/stuck_in_the_wrong_career": ["betting_on_yourself"],
    "friends/ross_geller/starting_over_after_divorce": ["rebuilding_after_being_left"],
    "friends/ross_geller/afraid_of_being_left_again": ["control_so_no_one_leaves", "letting_love_in"],
    # Money Heist
    "money_heist/the_professor/the_plan_versus_the_heart": ["carrying_a_secret_alone", "letting_love_in"],
    "money_heist/the_professor/responsible_for_everyone": ["weight_of_leading"],
    "money_heist/tokyo/running_from_the_past": ["outrunning_pain", "dropping_the_armour"],
    "money_heist/tokyo/love_versus_freedom": ["partners_want_different_lives", "letting_love_in"],
    "money_heist/berlin/nothing_left_to_lose": ["power_going_to_your_head", "taking_stock_of_a_life"],
    "money_heist/berlin/believing_in_love_again": ["letting_love_in", "hidden_love"],
    "money_heist/nairobi/getting_her_son_back": ["second_chance_as_a_parent", "can_you_really_change"],
    "money_heist/nairobi/taking_charge": ["fighting_for_respect", "promoted_over_peers"],
    "money_heist/denver/his_fathers_son": ["family_secret_rewrites_story", "loving_family_who_do_harm"],
    "money_heist/denver/unexpected_family": ["unready_parent", "unlikely_bond"],
    "money_heist/rio/all_in_on_first_love": ["lost_inside_one_relationship", "holding_on_to_someone_pulling_away"],
    "money_heist/rio/after_the_trauma": ["relearning_safety_after_abuse"],
    "money_heist/raquel_murillo/trusting_again": ["relearning_safety_after_abuse", "letting_love_in"],
    "money_heist/raquel_murillo/choosing_a_new_life": ["betting_on_yourself"],
    "money_heist/helsinki/the_gentle_giant": ["fix_someone_you_cant_save"],
    "money_heist/helsinki/loving_a_guarded_heart": ["holding_on_to_someone_pulling_away", "hidden_love"],
    # My Hero Academia
    "my_hero_academia/izuku_midoriya/the_kid_who_was_told_no": ["ordinary_among_gifted", "fighting_for_respect"],
    "my_hero_academia/izuku_midoriya/living_up_to_a_legacy": ["shoes_you_cant_fill"],
    "my_hero_academia/izuku_midoriya/carrying_it_alone": ["carrying_a_secret_alone"],
    "my_hero_academia/katsuki_bakugo/the_prodigy_meets_his_equals": ["worth_only_when_winning"],
    "my_hero_academia/katsuki_bakugo/facing_the_person_he_hurt": ["earning_back_trust"],
    "my_hero_academia/shoto_todoroki/refusing_his_fathers_half": ["breaking_the_family_cycle", "family_legacy_weight"],
    "my_hero_academia/shoto_todoroki/reaching_for_family": ["loving_family_who_do_harm"],
    "my_hero_academia/ochaco_uraraka/working_for_her_family": ["parentified_child", "ordinary_among_gifted"],
    "my_hero_academia/ochaco_uraraka/reaching_out_to_an_enemy": ["forgive_or_get_even", "pretending_fine_after_trauma"],
    "my_hero_academia/all_might/the_pillar_running_out_of_time": ["strong_one_cracks", "carrying_a_secret_alone"],
    "my_hero_academia/all_might/finding_worth_beyond_strength": ["reinvention_after_losing_role", "body_blow"],
    "my_hero_academia/shota_aizawa/tough_love_teacher": ["protective_love_becomes_control", "stuck_in_grief"],
    "my_hero_academia/shota_aizawa/unexpected_guardian": ["reluctant_guardian"],
    "my_hero_academia/tenya_iida/by_the_book_leader": ["promoted_over_peers", "conscience_vs_institution"],
    "my_hero_academia/tenya_iida/grief_and_revenge": ["revenge_as_identity"],
    "my_hero_academia/endeavor/forever_second_best": ["worth_only_when_winning"],
    "my_hero_academia/endeavor/atoning_too_late": ["earning_back_trust", "can_you_really_change"],
    # Schitt's Creek
    "schitts_creek/johnny_rose/starting_over_from_zero": ["reinvention_after_losing_role"],
    "schitts_creek/johnny_rose/absent_father_to_cheerleader": ["second_chance_as_a_parent"],
    "schitts_creek/moira_rose/clinging_to_former_glory": ["reinvention_after_losing_role"],
    "schitts_creek/moira_rose/learning_to_mother": ["second_chance_as_a_parent"],
    "schitts_creek/david_rose/letting_himself_be_loved": ["letting_love_in", "dropping_the_armour"],
    "schitts_creek/david_rose/building_his_own_thing": ["betting_on_yourself", "reinvention_after_losing_role"],
    "schitts_creek/alexis_rose/earning_her_own_way": ["tired_of_being_protected", "reinvention_after_losing_role"],
    "schitts_creek/alexis_rose/love_that_asks_something": ["partners_want_different_lives", "love_you_couldnt_keep"],
    "schitts_creek/stevie_budd/stuck_local_steps_up": ["dropping_the_armour"],
    "schitts_creek/stevie_budd/what_else_could_i_be": ["betting_on_yourself", "taking_stock_of_a_life"],
    "schitts_creek/patrick_brewer/living_true_to_himself": ["discovering_who_you_love", "find_your_voice"],
    "schitts_creek/roland_schitt/petty_power_to_true_friend": ["power_going_to_your_head"],
    "schitts_creek/twyla_sands/kindness_despite_chaos": ["find_your_voice"],
    # Squid Game
    "squid_game/seong_gi_hun/the_screw_up_who_wants_to_do_right": ["earning_back_trust", "crossing_a_line_under_pressure"],
    "squid_game/seong_gi_hun/the_crusade_against_the_system": ["guilt_into_care", "blaming_yourself"],
    "squid_game/cho_sang_woo/the_golden_boy_who_fell": ["worth_only_when_winning", "crossing_a_line_under_pressure"],
    "squid_game/kang_sae_byeok/the_loner_who_trusts_no_one": ["dropping_the_armour", "parentified_child"],
    "squid_game/oh_il_nam/one_last_game": ["taking_stock_of_a_life"],
    "squid_game/ali_abdul/a_trusting_outsider": ["dream_isnt_what_promised"],
    "squid_game/hwang_jun_ho/searching_for_a_missing_brother": ["loving_family_who_do_harm", "conscience_vs_institution"],
    "squid_game/ji_yeong/one_real_friend": ["numb_after_collapse", "unlikely_bond"],
    "squid_game/jang_deok_su/ruling_through_fear": ["control_so_no_one_leaves", "power_going_to_your_head"],
    # Stranger Things
    "stranger_things/eleven/learning_what_a_friend_is": ["leaving_controlling_group", "relearning_safety_after_abuse"],
    "stranger_things/eleven/who_am_i_without_it": ["reinvention_after_losing_role", "worth_only_when_winning"],
    "stranger_things/mike_wheeler/refusing_to_give_up_on_a_friend": ["fix_someone_you_cant_save"],
    "stranger_things/mike_wheeler/afraid_of_not_being_needed": ["ordinary_among_gifted", "stuck_in_grief"],
    "stranger_things/will_byers/nobody_understands_what_i_went_through": ["pretending_fine_after_trauma"],
    "stranger_things/will_byers/afraid_to_be_seen": ["discovering_who_you_love", "hidden_love"],
    "stranger_things/dustin_henderson/an_unlikely_big_brother": ["unlikely_bond"],
    "stranger_things/dustin_henderson/standing_by_a_misjudged_friend": ["conscience_vs_institution", "stuck_in_grief"],
    "stranger_things/max_mayfield/belonging_while_home_is_unsafe": ["dropping_the_armour", "loving_family_who_do_harm"],
    "stranger_things/max_mayfield/grief_she_cant_say_out_loud": ["blaming_yourself", "numb_after_collapse"],
    "stranger_things/jim_hopper/numbing_a_grief_he_wont_face": ["numb_after_collapse", "purpose_from_being_needed"],
    "stranger_things/jim_hopper/a_father_afraid_to_lose_again": ["protective_love_becomes_control"],
    "stranger_things/joyce_byers/the_mother_no_one_believes": ["trusting_your_instincts"],
    "stranger_things/joyce_byers/loving_without_holding_back": ["protective_love_becomes_control"],
    "stranger_things/steve_harrington/from_popular_jerk_to_protector": ["giving_yourself_up_to_belong", "purpose_from_being_needed"],
    "stranger_things/steve_harrington/life_after_peaking_early": ["reinvention_after_losing_role", "longing_for_a_family_of_your_own"],
    # Ted Lasso
    "ted_lasso/ted_lasso/leading_without_knowing_the_rules": ["promoted_over_peers"],
    "ted_lasso/ted_lasso/behind_the_smile": ["outrunning_pain", "strong_one_cracks"],
    "ted_lasso/ted_lasso/parenting_from_across_an_ocean": ["calling_vs_love"],
    "ted_lasso/rebecca_welton/from_revenge_to_healing": ["revenge_as_identity", "rebuilding_after_being_left"],
    "ted_lasso/rebecca_welton/letting_herself_want_again": ["longing_for_a_family_of_your_own", "learning_what_you_deserve_in_love"],
    "ted_lasso/roy_kent/who_am_i_after_this": ["reinvention_after_losing_role"],
    "ted_lasso/roy_kent/letting_someone_in": ["dropping_the_armour", "letting_love_in"],
    "ted_lasso/roy_kent/leading_the_ones_he_once_fought": ["promoted_over_peers", "unlikely_bond"],
    "ted_lasso/keeley_jones/taken_seriously": ["fighting_for_respect"],
    "ted_lasso/keeley_jones/choosing_herself": ["learning_what_you_deserve_in_love", "lost_inside_one_relationship"],
    "ted_lasso/jamie_tartt/the_fathers_voice": ["approval_from_withholding_parent", "dropping_the_armour"],
    "ted_lasso/jamie_tartt/from_star_to_teammate": ["earning_back_trust"],
    "ted_lasso/nate_shelley/hungry_to_be_seen": ["starving_to_matter", "earning_back_trust"],
    "ted_lasso/leslie_higgins/finding_his_spine": ["complicit_in_bad_organisation", "find_your_voice"],
    "ted_lasso/sam_obisanya/far_from_home": ["between_two_worlds", "dream_isnt_what_promised"],
    "ted_lasso/sam_obisanya/doing_the_right_thing": ["conscience_vs_institution"],
    # The Office
    "the_office/michael_scott/wanting_to_be_liked_by_his_team": ["starving_to_matter", "promoted_over_peers"],
    "the_office/michael_scott/longing_for_someone_to_come_home_to": ["longing_for_a_family_of_your_own", "learning_what_you_deserve_in_love"],
    "the_office/michael_scott/walking_away_to_start_over": ["betting_on_yourself", "reinvention_after_losing_role"],
    "the_office/jim_halpert/in_love_with_a_friend_who_is_taken": ["hidden_love"],
    "the_office/jim_halpert/betting_on_the_dream": ["calling_vs_love", "betting_on_yourself"],
    "the_office/pam_beesly/finding_her_voice": ["find_your_voice"],
    "the_office/pam_beesly/testing_the_dream_once_its_real": ["dream_isnt_what_promised"],
    "the_office/pam_beesly/holding_it_together_alone": ["partners_want_different_lives", "calling_vs_love"],
    "the_office/dwight_schrute/craving_authority": ["power_going_to_your_head", "starving_to_matter"],
    "the_office/dwight_schrute/a_love_he_cant_show": ["holding_on_to_someone_pulling_away"],
    "the_office/andy_bernard/needing_everyone_to_like_him": ["measured_against_a_sibling", "giving_yourself_up_to_belong"],
    "the_office/andy_bernard/chasing_a_dream_late": ["betting_on_yourself"],
    "the_office/ryan_howard/in_a_hurry_to_be_somebody": ["power_going_to_your_head", "starving_to_matter"],
    "the_office/ryan_howard/reinventing_instead_of_growing_up": ["starving_to_matter", "persona_replacing_you"],
    "the_office/erin_hannon/looking_for_family_at_work": ["giving_yourself_up_to_belong", "longing_for_a_family_of_your_own"],
    "the_office/erin_hannon/learning_she_deserves_better": ["learning_what_you_deserve_in_love"],
    "the_office/angela_martin/keeping_everything_under_control": ["dropping_the_armour", "persona_replacing_you"],
    "the_office/angela_martin/starting_over_from_the_bottom": ["reinvention_after_losing_role", "can_you_really_change"],
    # The Walking Dead
    "walking_dead/rick_grimes/carrying_everyones_survival": ["weight_of_leading", "crossing_a_line_under_pressure"],
    "walking_dead/rick_grimes/coming_home_changed": ["partners_want_different_lives"],
    "walking_dead/rick_grimes/choosing_the_future_over_revenge": ["forgive_or_get_even"],
    "walking_dead/daryl_dixon/outsider_finds_a_family": ["family_wrote_you_off", "dropping_the_armour"],
    "walking_dead/daryl_dixon/learning_to_stay": ["letting_love_in", "reluctant_guardian"],
    "walking_dead/carol_peletier/from_meek_to_formidable": ["find_your_voice", "relearning_safety_after_abuse"],
    "walking_dead/carol_peletier/the_weight_of_being_strong": ["strong_one_cracks"],
    "walking_dead/carol_peletier/grief_that_wants_someone_to_pay": ["revenge_as_identity"],
    "walking_dead/glenn_rhee/finding_his_own_voice": ["find_your_voice"],
    "walking_dead/glenn_rhee/love_in_the_worst_of_times": ["love_you_couldnt_keep"],
    "walking_dead/maggie_greene/stepping_out_of_her_fathers_world": ["tired_of_being_protected", "between_two_worlds"],
    "walking_dead/maggie_greene/leading_through_grief": ["weight_of_leading", "revenge_as_identity"],
    "walking_dead/michonne/letting_people_back_in": ["stuck_in_grief", "letting_love_in"],
    "walking_dead/michonne/the_guarded_protector": ["protective_love_becomes_control"],
    "walking_dead/carl_grimes/growing_up_too_fast": ["tired_of_being_protected", "parentified_child"],
    "walking_dead/carl_grimes/choosing_hope": ["forgive_or_get_even", "find_your_voice"],
    "walking_dead/eugene_porter/worth_more_than_a_title": ["ordinary_among_gifted", "outsider_learning_to_belong"],
    "walking_dead/eugene_porter/safety_at_what_price": ["complicit_in_bad_organisation"],
    # Arcane
    "arcane/vi/holding_everyone_together": ["parentified_child", "weight_of_leading"],
    "arcane/vi/searching_for_her_sister": ["earning_back_trust", "blaming_yourself"],
    "arcane/powder/desperate_to_be_useful": ["tired_of_being_protected", "family_wrote_you_off"],
    "arcane/jayce_talis/dream_called_reckless": ["betting_on_yourself", "unlikely_bond"],
    "arcane/jayce_talis/when_success_changes_you": ["power_going_to_your_head", "crossing_a_line_under_pressure"],
    "arcane/viktor/overlooked_genius_finds_a_partner": ["fighting_for_respect", "unlikely_bond"],
    "arcane/viktor/racing_the_clock": ["taking_stock_of_a_life", "body_blow"],
    "arcane/caitlyn_kiramman/privileged_idealist": ["betting_on_yourself", "tired_of_being_protected"],
    "arcane/caitlyn_kiramman/grief_wants_someone_to_pay": ["revenge_as_identity"],
    "arcane/silco/an_old_wound_as_a_mission": ["revenge_as_identity", "power_going_to_your_head"],
    "arcane/silco/the_cause_or_the_child": ["calling_vs_love", "reluctant_guardian"],
    "arcane/vander/keeping_the_peace": ["can_you_really_change", "carrying_a_secret_alone"],
    "arcane/ekko/growing_up_too_fast": ["parentified_child", "weight_of_leading"],
    "arcane/ekko/the_life_he_could_have_had": ["role_you_never_asked_for", "love_you_couldnt_keep"],
    # Brooklyn Nine-Nine
    "brooklyn_99/jake_peralta/the_case_of_growing_up": ["finally_growing_up", "breaking_the_family_cycle"],
    "brooklyn_99/jake_peralta/falling_for_his_rival": ["unlikely_bond", "letting_love_in"],
    "brooklyn_99/raymond_holt/earning_the_command": ["fighting_for_respect", "weight_of_leading"],
    "brooklyn_99/raymond_holt/letting_feelings_show": ["dropping_the_armour"],
    "brooklyn_99/amy_santiago/chasing_approval_and_the_top_job": ["worth_only_when_winning", "measured_against_a_sibling"],
    "brooklyn_99/rosa_diaz/walls_up": ["dropping_the_armour", "letting_love_in"],
    "brooklyn_99/rosa_diaz/telling_her_family_who_she_is": ["discovering_who_you_love", "family_wrote_you_off"],
    "brooklyn_99/terry_jeffords/afraid_to_get_hurt": ["fear_making_your_choices", "strong_one_cracks"],
    "brooklyn_99/terry_jeffords/speaking_up_at_a_cost": ["conscience_vs_institution", "fighting_for_respect"],
    "brooklyn_99/charles_boyle/loving_too_hard": ["control_so_no_one_leaves", "rebuilding_after_being_left"],
    "brooklyn_99/charles_boyle/becoming_a_father": ["longing_for_a_family_of_your_own"],
    "brooklyn_99/gina_linetti/meant_for_more": ["betting_on_yourself", "dropping_the_armour"],
    # Dark
    "dark/jonas_kahnwald/searching_for_why": ["family_secret_rewrites_story", "stuck_in_grief"],
    "dark/jonas_kahnwald/first_love_and_best_friend": ["love_you_couldnt_keep"],
    "dark/jonas_kahnwald/taking_it_on_himself": ["blaming_yourself", "role_you_never_asked_for"],
    "dark/martha_nielsen/torn_between_two_boys": ["torn_between_two_loves", "holding_on_to_someone_pulling_away"],
    "dark/martha_nielsen/choosing_her_own_path": ["leaving_controlling_group", "role_you_never_asked_for"],
    "dark/ulrich_nielsen/a_father_who_wont_stop_searching": ["stuck_in_grief", "blaming_yourself"],
    "dark/ulrich_nielsen/living_a_double_life": ["affair_breaks_the_trust"],
    "dark/charlotte_doppler/keeping_order_when_nothing_makes_sense": ["strong_one_cracks", "weight_of_leading"],
    "dark/charlotte_doppler/where_she_comes_from": ["family_secret_rewrites_story"],
    "dark/hannah_kahnwald/wanting_what_isnt_hers": ["control_so_no_one_leaves", "holding_on_to_someone_pulling_away"],
    "dark/hannah_kahnwald/starting_over_alone": ["unready_parent", "dream_isnt_what_promised"],
    "dark/claudia_tiedemann/career_before_family": ["calling_vs_love", "second_chance_as_a_parent"],
    "dark/claudia_tiedemann/whatever_it_takes_for_her_daughter": ["second_chance_as_a_parent", "crossing_a_line_under_pressure"],
    "dark/katharina_nielsen/holding_the_family_together": ["affair_breaks_the_trust", "strong_one_cracks"],
    "dark/katharina_nielsen/going_back_for_her_family": ["forgive_or_get_even", "relearning_safety_after_abuse"],
    "dark/regina_tiedemann/old_wounds_that_never_healed": ["forgive_or_get_even", "approval_from_withholding_parent"],
    "dark/regina_tiedemann/holding_on_while_everything_slips": ["body_blow", "strong_one_cracks"],
    # Fullmetal Alchemist
    "fma/edward_elric/carrying_the_blame_alone": ["blaming_yourself", "guilt_into_care"],
    "fma/edward_elric/anger_at_an_absent_father": ["making_peace_with_a_parent"],
    "fma/edward_elric/working_for_a_system_you_distrust": ["complicit_in_bad_organisation", "conscience_vs_institution"],
    "fma/alphonse_elric/am_i_still_real": ["body_blow"],
    "fma/alphonse_elric/the_steady_younger_sibling": ["helper_with_no_needs", "forgive_or_get_even"],
    "fma/roy_mustang/climbing_to_change_the_system": ["guilt_into_care", "can_you_really_change"],
    "fma/roy_mustang/when_grief_becomes_vengeance": ["revenge_as_identity", "forgive_or_get_even"],
    "fma/riza_hawkeye/living_with_what_she_has_done": ["guilt_into_care"],
    "fma/winry_rockbell/the_one_who_waits_at_home": ["holding_on_to_someone_pulling_away", "helper_with_no_needs"],
    "fma/winry_rockbell/choosing_not_to_pull_the_trigger": ["forgive_or_get_even"],
    "fma/scar/consumed_by_revenge": ["revenge_as_identity"],
    "fma/scar/facing_the_harm_he_caused": ["can_you_really_change", "guilt_into_care"],
    "fma/ling_yao/carrying_a_clans_hopes": ["family_legacy_weight", "weight_of_leading"],
    "fma/ling_yao/what_makes_a_true_leader": ["weight_of_leading"],
    "fma/izumi_curtis/a_grief_she_never_speaks_of": ["blaming_yourself", "stuck_in_grief"],
    "fma/izumi_curtis/tough_love_for_kids_not_her_own": ["guiding_someone_who_resists"],
    # Gilmore Girls
    "gilmore_girls/lorelai_gilmore/going_back_to_the_family_she_fled": ["making_peace_with_a_parent", "approval_from_withholding_parent"],
    "gilmore_girls/lorelai_gilmore/building_her_own_inn": ["betting_on_yourself"],
    "gilmore_girls/lorelai_gilmore/letting_someone_all_the_way_in": ["letting_love_in", "torn_between_two_loves"],
    "gilmore_girls/rory_gilmore/living_up_to_the_plan": ["worth_only_when_winning", "dream_isnt_what_promised"],
    "gilmore_girls/rory_gilmore/adrift_in_her_thirties": ["adrift_looking_for_a_calling", "taking_stock_of_a_life"],
    "gilmore_girls/emily_gilmore/earning_a_place_in_her_daughters_life": ["protective_love_becomes_control", "making_peace_with_a_parent"],
    "gilmore_girls/emily_gilmore/marriage_on_the_rocks": ["affair_breaks_the_trust", "partners_want_different_lives"],
    "gilmore_girls/emily_gilmore/starting_over_late_in_life": ["reinvention_after_losing_role", "stuck_in_grief"],
    "gilmore_girls/richard_gilmore/reaching_the_daughter_he_lost": ["second_chance_as_a_parent", "making_peace_with_a_parent"],
    "gilmore_girls/richard_gilmore/who_he_is_without_his_job": ["reinvention_after_losing_role"],
    "gilmore_girls/luke_danes/the_guarded_heart": ["hidden_love", "dropping_the_armour"],
    "gilmore_girls/luke_danes/responsibility_he_never_asked_for": ["reluctant_guardian", "guiding_someone_who_resists"],
    "gilmore_girls/lane_kim/living_a_double_life": ["persona_replacing_you", "between_two_worlds"],
    "gilmore_girls/lane_kim/life_outruns_her_plans": ["unready_parent", "calling_vs_love"],
    "gilmore_girls/paris_geller/perfection_as_armor": ["worth_only_when_winning", "dropping_the_armour"],
    "gilmore_girls/paris_geller/leading_without_driving_everyone_away": ["promoted_over_peers", "weight_of_leading"],
    "gilmore_girls/sookie_st_james/panicking_at_every_big_step": ["fear_making_your_choices"],
    "gilmore_girls/sookie_st_james/betting_on_a_shared_dream": ["betting_on_yourself"],
    # Mad Men
    "mad_men/don_draper/the_man_behind_the_pitch": ["persona_replacing_you", "dropping_the_armour"],
    "mad_men/don_draper/drinking_through_the_emptiness": ["numbing_habit"],
    "mad_men/don_draper/becoming_the_father_he_never_had": ["breaking_the_family_cycle"],
    "mad_men/peggy_olson/from_the_typing_pool_to_the_table": ["fighting_for_respect"],
    "mad_men/peggy_olson/stepping_out_of_the_mentors_shadow": ["betting_on_yourself"],
    "mad_men/joan_holloway/the_plan_she_was_raised_for": ["dream_isnt_what_promised", "learning_what_you_deserve_in_love"],
    "mad_men/joan_holloway/fighting_to_be_taken_seriously": ["fighting_for_respect"],
    "mad_men/pete_campbell/never_enough_for_anyone": ["approval_from_withholding_parent", "starving_to_matter"],
    "mad_men/pete_campbell/the_life_he_thought_he_wanted": ["dream_isnt_what_promised", "affair_breaks_the_trust"],
    "mad_men/roger_sterling/the_party_that_cant_last": ["taking_stock_of_a_life", "finally_growing_up"],
    "mad_men/roger_sterling/proving_he_still_matters": ["reinvention_after_losing_role"],
    "mad_men/betty_draper/the_perfect_wife_with_numb_hands": ["find_your_voice", "lost_inside_one_relationship"],
    "mad_men/betty_draper/mother_who_was_never_mothered": ["breaking_the_family_cycle"],
    "mad_men/sally_draper/the_child_who_sees_everything": ["loving_family_who_do_harm", "family_secret_rewrites_story"],
    "mad_men/sally_draper/refusing_to_become_her_parents": ["breaking_the_family_cycle", "making_peace_with_a_parent"],
    "mad_men/megan_calvet/choosing_her_own_dream": ["betting_on_yourself", "calling_vs_love"],
    # Parks and Recreation
    "parks_and_rec/leslie_knope/dreaming_big_from_the_bottom_rung": ["fighting_for_respect"],
    "parks_and_rec/leslie_knope/when_the_heart_and_the_dream_collide": ["calling_vs_love"],
    "parks_and_rec/ron_swanson/the_man_who_wants_to_be_left_alone": ["dropping_the_armour"],
    "parks_and_rec/ron_swanson/the_ex_he_cant_stay_away_from": ["learning_what_you_deserve_in_love"],
    "parks_and_rec/ben_wyatt/living_down_a_youthful_failure": ["can_you_really_change"],
    "parks_and_rec/april_ludgate/pretending_not_to_care": ["dropping_the_armour"],
    "parks_and_rec/april_ludgate/what_do_you_want_to_do_with_your_life": ["adrift_looking_for_a_calling"],
    "parks_and_rec/andy_dwyer/growing_up_after_being_left": ["finally_growing_up", "rebuilding_after_being_left"],
    "parks_and_rec/andy_dwyer/looking_for_what_hes_good_at": ["adrift_looking_for_a_calling"],
    "parks_and_rec/tom_haverford/the_mogul_in_waiting": ["betting_on_yourself", "persona_replacing_you"],
    "parks_and_rec/tom_haverford/playing_the_field_to_avoid_getting_hurt": ["letting_love_in", "dropping_the_armour"],
    "parks_and_rec/ann_perkins/finding_herself_outside_a_relationship": ["lost_inside_one_relationship"],
    "parks_and_rec/ann_perkins/building_a_family_on_her_own_terms": ["longing_for_a_family_of_your_own"],
    "parks_and_rec/chris_traeger/positivity_as_a_shield": ["outrunning_pain", "strong_one_cracks"],
    # Sex Education
    "sex_education/otis_milburn/the_advice_giver": ["helper_with_no_needs"],
    "sex_education/otis_milburn/growing_up_under_a_parent_who_knows_too_much": ["tired_of_being_protected", "parentified_child"],
    "sex_education/otis_milburn/falling_for_his_business_partner": ["hidden_love", "love_you_couldnt_keep"],
    "sex_education/maeve_wiley/raising_herself": ["parentified_child", "making_peace_with_a_parent"],
    "sex_education/maeve_wiley/the_gifted_outsider": ["betting_on_yourself", "fighting_for_respect"],
    "sex_education/maeve_wiley/letting_her_guard_down": ["letting_love_in", "dropping_the_armour"],
    "sex_education/eric_effiong/being_himself_out_loud": ["between_two_worlds", "discovering_who_you_love"],
    "sex_education/eric_effiong/what_he_deserves_in_love": ["learning_what_you_deserve_in_love"],
    "sex_education/jean_milburn/the_expert_who_cant_fix_her_own_home": ["letting_love_in", "protective_love_becomes_control"],
    "sex_education/jean_milburn/when_the_helper_needs_help": ["strong_one_cracks", "making_peace_with_a_parent"],
    "sex_education/adam_groff/the_bully_who_hates_himself": ["dropping_the_armour", "can_you_really_change"],
    "sex_education/adam_groff/finding_what_hes_good_at": ["adrift_looking_for_a_calling", "family_wrote_you_off"],
    "sex_education/aimee_gibbs/finding_out_what_she_wants": ["find_your_voice", "giving_yourself_up_to_belong"],
    "sex_education/aimee_gibbs/feeling_safe_in_her_body_again": ["relearning_safety_after_abuse", "pretending_fine_after_trauma"],
    "sex_education/jackson_marchetti/the_golden_boy_under_pressure": ["worth_only_when_winning", "strong_one_cracks"],
    "sex_education/jackson_marchetti/who_he_is_beyond_the_image": ["discovering_who_you_love", "family_secret_rewrites_story"],
    "sex_education/ruby_matthews/the_queen_bee_armour": ["dropping_the_armour"],
    "sex_education/ruby_matthews/starting_over_without_a_crown": ["reinvention_after_losing_role", "forgive_or_get_even"],
    # Succession
    "succession/logan_roy/refusing_to_let_go": ["control_so_no_one_leaves", "taking_stock_of_a_life"],
    "succession/logan_roy/the_childhood_he_never_mentions": ["dropping_the_armour", "making_peace_with_a_parent"],
    "succession/kendall_roy/chasing_his_fathers_chair": ["approval_from_withholding_parent", "family_legacy_weight"],
    "succession/kendall_roy/staying_sober_under_pressure": ["numbing_habit", "earning_back_trust"],
    "succession/shiv_roy/claiming_a_seat_at_the_table": ["approval_from_withholding_parent", "fighting_for_respect"],
    "succession/shiv_roy/love_on_her_own_terms": ["letting_love_in", "partners_want_different_lives"],
    "succession/roman_roy/the_joker_who_wants_to_be_taken_seriously": ["approval_from_withholding_parent", "family_wrote_you_off"],
    "succession/roman_roy/closeness_only_as_a_joke": ["letting_love_in", "dropping_the_armour"],
    "succession/connor_roy/the_forgotten_eldest": ["starving_to_matter"],
    "succession/connor_roy/paying_for_love": ["letting_love_in"],
    "succession/tom_wambsgans/the_outsider_who_wants_in": ["giving_yourself_up_to_belong", "complicit_in_bad_organisation"],
    "succession/tom_wambsgans/loving_someone_who_holds_the_power": ["learning_what_you_deserve_in_love"],
    "succession/greg_hirsch/learning_the_price_of_getting_ahead": ["complicit_in_bad_organisation", "giving_yourself_up_to_belong"],
    "succession/gerri_kellman/competent_and_overlooked": ["fighting_for_respect", "complicit_in_bad_organisation"],
    # The Good Place
    "the_good_place/eleanor_shellstrop/earning_her_place": ["can_you_really_change"],
    "the_good_place/eleanor_shellstrop/letting_people_in": ["letting_love_in", "dropping_the_armour"],
    "the_good_place/eleanor_shellstrop/responsible_for_others": ["weight_of_leading", "role_you_never_asked_for"],
    "the_good_place/chidi_anagonye/choosing_without_certainty": ["fear_making_your_choices"],
    "the_good_place/chidi_anagonye/loving_his_opposite": ["unlikely_bond", "fear_making_your_choices"],
    "the_good_place/tahani_al_jamil/outside_her_sisters_shadow": ["measured_against_a_sibling", "approval_from_withholding_parent"],
    "the_good_place/tahani_al_jamil/who_she_is_without_an_audience": ["reinvention_after_losing_role", "adrift_looking_for_a_calling"],
    "the_good_place/jason_mendoza/behind_the_silence": ["giving_yourself_up_to_belong", "persona_replacing_you"],
    "the_good_place/jason_mendoza/thinking_before_acting": ["finally_growing_up"],
    "the_good_place/michael/first_big_project": ["conscience_vs_institution", "complicit_in_bad_organisation"],
    "the_good_place/michael/learning_from_his_charges": ["taking_stock_of_a_life", "reinvention_after_losing_role"],
    "the_good_place/janet/more_than_a_helper": ["helper_with_no_needs", "find_your_voice"],
    "the_good_place/janet/feelings_she_wasnt_built_for": ["love_you_couldnt_keep"],
}

def main():
    patterns = [{"id": f"pattern:theme_{s}", "label": l, "description": d, "broader": []}
                for s, l, d in THEMES]
    patterns += [{"id": f"pattern:{s}", "label": l, "description": d,
                  "broader": [f"pattern:theme_{t}" for t in th]}
                 for s, l, d, th in PATTERNS]
    assign = {f"arc:{a}": [f"pattern:{p}" for p in ps] for a, ps in ASSIGN.items()}
    out = os.path.join(HERE, "patterns.json")
    with open(out, "w") as f:
        json.dump({"patterns": patterns, "assign": assign}, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"wrote {out}: {len(THEMES)} themes, {len(PATTERNS)} patterns, {len(assign)} arcs")

if __name__ == "__main__":
    main()
