import { Platform } from 'react-native';

/**
 * Register the PWA service worker (dist/sw.js, generated by `npm run build:pwa`).
 * Production web only: the Metro dev server doesn't serve sw.js, and caching
 * would interfere with live preview anyway.
 */
export function registerServiceWorker(): void {
  if (Platform.OS !== 'web' || typeof window === 'undefined') return;
  if (process.env.NODE_ENV !== 'production') return;
  if (!('serviceWorker' in navigator)) return;

  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {
      // Registration is best-effort; the app works without offline support.
    });
  });
}
